# Generated by Django 4.2.2 on 2023-07-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
    ]
