# Generated by Django 4.2.2 on 2023-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_phone',
            field=models.CharField(default='0867923813', max_length=10),
            preserve_default=False,
        ),
    ]
