# Generated by Django 4.2.2 on 2023-07-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='gmail',
            field=models.CharField(default='user@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
