# Generated by Django 4.2.2 on 2023-08-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-rate',)},
        ),
    ]
