# Generated by Django 4.2.2 on 2023-08-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_rate_productrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrate',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shop.productrate'),
            preserve_default=False,
        ),
    ]
