# Generated by Django 4.2.2 on 2023-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_options_remove_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='avg_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
