# Generated by Django 4.2.2 on 2023-08-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_rate_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
